title: Les petits poissons d’Odette
description: Un blog pour parler maternage et projet d’accouchement physiologique

url: http://ogoldfish.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Accueil
   url: /index.html
 - title: À propos
   url: /about.html

social:
   twitter: odetteGoldfish

google_analytics: "UA-62090058-1"
