title: Les petits poissons d’Odette
description: Un blog pour parler maternage et projet d’accouchement physiologique

url: http://ogoldfish.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   twitter: odetteGoldfish

google_analytics: "UA-58263416-1"
